# tasks file
---
- name: Generate
  import_tasks: generate.yml
  tags:
    - configuration
    - ssh-keys
    - ssh-keys-generate

# - name: Private-keys
#   ansible.builtin.import_tasks: private-keys.yml
#   tags:
#     - configuration
#     - ssh-keys
#     - ssh-keys-private-keys
#
# - name: Public-keys
#   ansible.builtin.import_tasks: public-keys.yml
#   tags:
#     - configuration
#     - ssh-keys
#     - ssh-keys-public-keys

- name: Authorized-keys
  import_tasks: authorized-keys.yml
  tags:
    - configuration
    - ssh-keys
    - ssh-keys-authorized-keys

- name: Security ssh
  import_tasks: security.yml
  tags:
    - configuration
    - sshd-rules
